### ISSUE TITLE
Precisamos tratar melhor a questao do salario

### ISSUE THREAD

**Issue by danielsilvafarias** [M4T3U5/Jobs-App#3]

**Comment by danielsilvafarias** [comment]
Quem puder dar uma olhada nisso. Salario pode ser por hora.

**Comment by M4T3U5** [comment]
Expandindo o estudo de caso, o atributo salário está ganhando muitas entradas. Sugiro a criação de uma classe, que atenda às necessidades do projeto

**Comment by danielsilvafarias** [comment]
@M4T3U5 Parece interessant. Vou criar uma classe no diagrama pra isso.

**Comment by danielsilvafarias** [comment]
Enviando diagrame atualizado
